### ISSUE TITLE
请问大佬，我看这两天叮咚更新了追加菜品的功能，是否会影响这个 repo 正常下单呢？

### ISSUE THREAD

**Issue by a180285** [Runc2333/dingdong-helper-node#1]

**Comment by Runc2333** [comment]
4.25已测试可以正常下单，抓包方式有改变，之前的令牌没有退出登录的可以继续用

------------------ 原始邮件 ------------------
发件人: HuangWei ***@***.***&gt;
发送时间: 2022年4月25日 12:27
收件人: Runc2333/dingdong-helper-node ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Runc2333/dingdong-helper-node] 请问大佬，我看这两天叮咚更新了追加菜品的功能，是否会影响这个 repo 正常下单呢？ (Issue #1)

**Comment by a180285** [comment]
感谢，因为之前用其他 java 代码，发现今天似乎下不了单。感谢大佬
