### ISSUE TITLE
［已解决］抓了iOS的包，想试试能不能逆向iOS签名算法

### ISSUE THREAD

**Issue by IMLR** [Runc2333/dingdong-helper-node#10]
代码加了跳过代理，不太好抓包，不过已经抓到了，此处先略过
node版本还没配置，在JAVA版试了一下，简单配置一下，不带验证可以获取到地址消息，可以全选购物车。
无法获取配送时间和下单，会返回人多拥挤。重放请求，大概十次请求后失效返回人多拥挤，不带签名或修改请求内容均会返回人多拥挤。
应该可以确认目前关键请求均带有验证，如果不还原签名算法应该是不能模拟APP请求进行下单。
看到逆向安卓APP想到了逆向iOS包，脱壳后看了一下代码，签名算法包括了sha和md5，但是能力不足还没啥进展，今天再试试吧
如果这边作者可以逆向APP成功，起码在接口这部分就不会被限制了，毕竟APP很难像小程序那样快速迭代

**Comment by Runc2333** [comment]
目前已经完成逆向安卓app了，并且成功算出了sesi,nars,sign，但还不能用js还原签名算法，因此无法发布。
如果可以协助的话，可以尝试逆向lib/armebai-v7a/libli11li1.so。

**Comment by IMLR** [comment]
> 目前已经完成逆向安卓app了，并且成功算出了sesi,nars,sign，但还不能用js还原签名算法，因此无法发布。 如果可以协助的话，可以尝试逆向lib/armebai-v7a/libli11li1.so。

我这边也逆向了iOS版了，能私下交流下吗

**Comment by Runc2333** [comment]
t.me/runc0321

**Comment by dreamer2q** [comment]
@Runc2333  原作者的仓库不是有一个 sign.js 用来计算签名吗？这个和你逆袭的有什么区别吗？

**Comment by Runc2333** [comment]
> @Runc2333 原作者的仓库不是有一个 sign.js 用来计算签名吗？这个和你逆袭的有什么区别吗？

原生app签名算法与各渠道小程序不同。

**Comment by dreamer2q** [comment]
> 目前已经完成逆向安卓app了，并且成功算出了sesi,nars,sign，但还不能用js还原签名算法，因此无法发布。

如果 js 还原签名成本较高，不能直接通过 ffi 方式作为一个外部库来调用吗?

**Comment by iiwen** [comment]
sesi,nars,sign用java什么的可以吗

**Comment by Runc2333** [comment]
> > 目前已经完成逆向安卓app了，并且成功算出了sesi,nars,sign，但还不能用js还原签名算法，因此无法发布。
> 
> 如果 js 还原签名成本较高，不能直接通过 ffi 方式作为一个外部库来调用吗?

原库使用jni调用，且需要安卓context，所以没法这么做。

**Comment by iiwen** [comment]
@Runc2333 安卓逆向我搞了半天没头绪，大佬你们后续打算怎么发布~
昨天我向某群提供了方案，大部分人都通过除微信外第二大渠道下单成功~

**Comment by yzkmt** [comment]
> @Runc2333 安卓逆向我搞了半天没头绪，大佬你们后续打算怎么发布~ 昨天我向某群提供了方案，大部分人都通过ali渠道下单成功~
大哥群能拉一下吗，孩子好久没下单成功了吃不到饭了。

**Comment by Star8Platinum** [comment]
> > > 目前已经完成逆向安卓app了，并且成功算出了sesi,nars,sign，但还不能用js还原签名算法，因此无法发布。
> > 
> > 
> > 如果 js 还原签名成本较高，不能直接通过 ffi 方式作为一个外部库来调用吗?
> 
> 原库使用jni调用，且需要安卓context，所以没法这么做。

这样的话能不能直接做成apk来使用jni呢，用虚拟机或者实机来跑

**Comment by IMLR** [comment]
> 

我和老哥已经把iOS版逆向完了，应该还是用node跑

**Comment by greggzj** [comment]
大佬们ios是否可以先发布呢，现在是不是就卡在那个sign字段拉

**Comment by Star8Platinum** [comment]
> > 
> 
> 我和老哥已经把iOS版逆向完了，应该还是用node跑

期待，我昨天尝试逆向了一下6.6的抢菜软件，然后卡在了反编译源代码，而且都混淆了，所以没成功，大佬加油

**Comment by Star8Platinum** [comment]
> 大佬们ios是否可以先发布呢，现在是不是就卡在那个sign字段拉

好像几天前开始校验sign了，搞不定的话应该也没用

**Comment by IMLR** [comment]
> 大佬们ios是否可以先发布呢，现在是不是就卡在那个sign字段拉

sign和nars和seid的算法都已经还原了，我只是逆向了签名算法，具体发布还得等这位大佬完全调试好吧

**Comment by greggzj** [comment]
> > 大佬们ios是否可以先发布呢，现在是不是就卡在那个sign字段拉
> 
> sign和nars和seid的算法都已经还原了，我只是逆向了签名算法，具体发布还得等这位大佬完全调试好吧

我也抓了ios的包，nars和seid原来都有，就是不太理解sign怎么计算出来的，囧。。应该就差这个了吧，有了sign一切好说了？

**Comment by IMLR** [comment]
> > > 大佬们ios是否可以先发布呢，现在是不是就卡在那个sign字段拉
> > 
> > 
> > sign和nars和seid的算法都已经还原了，我只是逆向了签名算法，具体发布还得等这位大佬完全调试好吧
> 
> 我也抓了ios的包，nars和seid原来都有，就是不太理解sign怎么计算出来的，囧。。应该就差这个了吧，有了sign一切好说了？

sign是最简单的，最麻烦的是nars和seid，这两个都是sign计算的

**Comment by greggzj** [comment]
> > > > 大佬们ios是否可以先发布呢，现在是不是就卡在那个sign字段拉
> > > 
> > > 
> > > sign和nars和seid的算法都已经还原了，我只是逆向了签名算法，具体发布还得等这位大佬完全调试好吧
> > 
> > 
> > 我也抓了ios的包，nars和seid原来都有，就是不太理解sign怎么计算出来的，囧。。应该就差这个了吧，有了sign一切好说了？
> 
> sign是最简单的，最麻烦的是nars和seid，这两个都是sign计算的

想请教下sign是如何计算的呀？有参考公式么？

**Comment by Minfee** [comment]
> > > 大佬们ios是否可以先发布呢，现在是不是就卡在那个sign字段拉
> > 
> > 
> > sign和nars和seid的算法都已经还原了，我只是逆向了签名算法，具体发布还得等这位大佬完全调试好吧
> 
> 我也抓了ios的包，nars和seid原来都有，就是不太理解sign怎么计算出来的，囧。。应该就差这个了吧，有了sign一切好说了？

想请教下是怎么抓包的，自己尝试了一下 发现绕过代理了，还没有头绪
