### ISSUE TITLE
为啥默认地址一直不能变呢

### ISSUE THREAD

**Issue by goodtiger** [Runc2333/dingdong-helper-node#11]
我抓包是另外一个地址A，但是程序跑起来一直是地址B，这是啥问题

**Comment by Runc2333** [comment]
请修改叮咚app内的默认地址，程序会主动获取设置的默认地址，抓包的地址会被覆盖。

**Comment by goodtiger** [comment]
> 请修改叮咚app内的默认地址，程序会主动获取设置的默认地址，抓包的地址会被覆盖。

多谢，可以了

**Comment by yuejiang** [comment]
> > 请修改叮咚app内的默认地址，程序会主动获取设置的默认地址，抓包的地址会被覆盖。
> 
> 多谢，可以了

请问银行参数，今天6点或者8点半成功了吗？

**Comment by goodtiger** [comment]
> > > 请修改叮咚app内的默认地址，程序会主动获取设置的默认地址，抓包的地址会被覆盖。
> > 
> > 
> > 多谢，可以了
> 
> 请问银行参数，今天6点或者8点半成功了吗？

下午刚弄好，捡漏了一单，但是支付没成功，明天上午看看
