### ISSUE TITLE
这个是什么错误啊？

### ISSUE THREAD

**Issue by jackiehj** [Runc2333/dingdong-helper-node#12]
[Jackie-HJdeMacBook-Pro:dingdong-helper-node-main Jackie$ yarn checkout:normal
yarn run v1.22.18
$ node scripts/checkout_cart
/Users/Jackie/Downloads/dingdong-helper-node-main/service/session_parser.js:79
        "ddmc-device-token": header.find(item => item.name.toLowerCase() == "ddmc-device-token").value,
                                                                                                ^

TypeError: Cannot read properties of undefined (reading 'value')
    at load_profile (/Users/Jackie/Downloads/dingdong-helper-node-main/service/session_parser.js:79:97)
    at /Users/Jackie/Downloads/dingdong-helper-node-main/scripts/checkout_cart.js:96:27
    at /Users/Jackie/Downloads/dingdong-helper-node-main/scripts/checkout_cart.js:162:11

Node.js v18.0.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by IMLR** [comment]
session里面没找到device token，检查一下保存的sesion是否正确

**Comment by jackiehj** [comment]
> session里面没找到device token，检查一下保存的sesion是否正确

好的，终于搞定了。新的文件Index有很多。保存错误了大概。
