### ISSUE TITLE
新功能讨论 | 考虑通过worker_threads之类的增加并发能力，倒计时执行功能

### ISSUE THREAD

**Issue by IMLR** [Runc2333/dingdong-helper-node#14]
今天实测下单成功
大约12秒成功下单，目前单次感觉性能上不如JAVA版本的，猜测是否因为JAVA并发请求？
通过worker_threads这类的是不是能够做到像JAVA版本那样并发请求提高性能呢？
当然也有可能只是纯纯的运气不好或者叮咚假库存🌚

另外可否加入传入启动参数以定时运行呢，虽然有别的办法可以做到，不过感觉传入启动参数以在特定时间运行会比较省心一点

**Comment by czqcs** [comment]
请问您有

service/dingdong/api/ios-native/_native_sign.js
service/dingdong/api/ios-native/_native_sign.encrypted.js
这两个文件吗

**Comment by IMLR** [comment]
> 请问您有
> 
> service/dingdong/api/ios-native/_native_sign.js service/dingdong/api/ios-native/_native_sign.encrypted.js 这两个文件吗

这两个文件应该是测试时候使用的，正式发的版本应该本来就没有？我这边用的是测试版的

**Comment by czqcs** [comment]
不知道是不是性能不够 今天我一件都没抢到

**Comment by czqcs** [comment]
debug看了一下 签名模块是正常的

**Comment by IMLR** [comment]
我个人觉得是跟并发有关，但是也有可能是地区问题，毕竟JAVA版作者也存在买不到的情况😂
另外跟本issue无关的内容还是先删掉吧

**Comment by czqcs** [comment]
> 我个人觉得是跟并发有关，但是也有可能是地区问题，毕竟JAVA版作者也存在买不到的情况😂 另外跟本issue无关的内容还是先删掉吧

小区群里还是很多人买到的，而且每一单东西还不少，不至于没他们手速快吧😂

**Comment by czqcs** [comment]
> 我个人觉得是跟并发有关，但是也有可能是地区问题，毕竟JAVA版作者也存在买不到的情况😂

我尝试写个多线程的试试 谢谢大佬的sign代码
