### ISSUE TITLE
求助～iOS端没有抓到 maicai.api.ddxq.mobi 这个包

### ISSUE THREAD

**Issue by ch-1008** [Runc2333/dingdong-helper-node#17]
<img width="255" alt="image" src="https://user-images.githubusercontent.com/82588006/166127992-7ec2ad8c-eb9f-4570-8228-447255f480e4.png">

**Comment by chaoyu** [comment]
> <img width="255" alt="image" src="https://user-images.githubusercontent.com/82588006/166127992-7ec2ad8c-eb9f-4570-8228-447255f480e4.png">
> 
> 

你点购物车按钮刷新了吗？点了才会有

**Comment by funnyData** [comment]
咋解决的啊？老哥，我也抓不到

**Comment by Runc2333** [comment]
> 咋解决的啊？老哥，我也抓不到

参见readme结尾
