### ISSUE TITLE
下单成功！感谢

### ISSUE THREAD

**Issue by MisakaMikoto86** [Runc2333/dingdong-helper-node#18]
今早8:30:20左右测试成功一单，非常感谢 @Runc2333 和@IMLR的努力。

祝大伙五一快乐（包括叮咚程序员XD），疫情期间天天有饭吃!

**Comment by saltapp** [comment]
请问你能抓到 maicai.api.ddxq.mobi 这个包么？

**Comment by IMLR** [comment]
你成功时间也是大于十秒钟吗？

**Comment by jzhone** [comment]
我 07 和 16 秒都成功下单了，只有 16 秒的时候提示成功，再去 app 刷新发现 07 已经下单成功了，不过两个订单的商品不一样

**Comment by Runc2333** [comment]
> 我 07 和 16 秒都成功下单了，只有 16 秒的时候提示成功，再去 app 刷新发现 07 已经下单成功了，不过两个订单的商品不一样

方便联系我发送一下日志吗？
t.me/runc0321

**Comment by jzhone** [comment]
> > 我 07 和 16 秒都成功下单了，只有 16 秒的时候提示成功，再去 app 刷新发现 07 已经下单成功了，不过两个订单的商品不一样
> 
> 方便联系我发送一下日志吗？ t.me/runc0321

已经发送
