### ISSUE TITLE
fix: 最好把对应的ddmc-build-version / api-version 写在md里

### ISSUE THREAD

**Issue by wegi8** [Runc2333/dingdong-helper-node#2]

**Comment by Runc2333** [comment]
目前是直接从抓到的包中提取的，所以理论上能抓到包就可以用。

**Comment by wegi8** [comment]
嗯嗯, 不过不是参数问题, 但是目前他的api正在改版, 原来部分接口还能使用, 后续应该(也许)整体url都会换掉, 所以一个version标识能够让人比较直观的判断, 这个repo能不能用

**Comment by Runc2333** [comment]
已换用建设银行api，已添加`api-version`和`app-version`
