### ISSUE TITLE
charles获取的Session没有ddmc-device-token导致运行报错

### ISSUE THREAD

**Issue by csrxff** [Runc2333/dingdong-helper-node#20]
Windows Powershell下运行时提示

PS D:\dingdong-helper-node-main> yarn checkout:normal
yarn run v1.22.18
$ node scripts/checkout_cart
D:\dingdong-helper-node-main\service\session_parser.js:79
        "ddmc-device-token": header.find(item => item.name.toLowerCase() == "ddmc-device-token").value,
                                                                                                ^

TypeError: Cannot read properties of undefined (reading 'value')
    at load_profile (D:\dingdong-helper-node-main\service\session_parser.js:79:97)
    at D:\dingdong-helper-node-main\scripts\checkout_cart.js:96:27
    at D:\dingdong-helper-node-main\scripts\checkout_cart.js:162:11

Node.js v17.0.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS D:\dingdong-helper-node-main>

看了下charles抓的https://maicai.api.ddxq.mobi/cart/index这个包下也确实没找到ddmc-device-token这个值
在Untitled.chlsj里手动添加token的空值后运行是这样提示了

PS D:\dingdong-helper-node-main> yarn checkout:normal
yarn run v1.22.18
$ node scripts/checkout_cart
[2022-05-01 10:11:25] [DEBUG] 尝试获取不存在的 Param: device_token
[2022-05-01 10:11:26] [INFO] [] 当前默认地址 : *********************
[2022-05-01 10:11:26] [DEBUG] 尝试获取不存在的 Param: device_token
[2022-05-01 10:11:26] [DEBUG] 尝试获取不存在的 Param: device_token
[2022-05-01 10:11:27] [ERROR] 获取购物车内容失败: 购物车无有货商品

这样是正常可运行吗

**Comment by waynez** [comment]
MacOS, 同样问题

```
% yarn checkout:normal
yarn run v1.22.18
$ node scripts/checkout_cart
/Users/zhengw/Repository/covid-cai/dingdong-helper-node/service/session_parser.js:79
        "ddmc-device-token": header.find(item => item.name.toLowerCase() == "ddmc-device-token").value,
                                                                                                ^

TypeError: Cannot read properties of undefined (reading 'value')
    at load_profile (/Users/zhengw/Repository/covid-cai/dingdong-helper-node/service/session_parser.js:79:97)
    at /Users/zhengw/Repository/covid-cai/dingdong-helper-node/scripts/checkout_cart.js:96:27
    at /Users/zhengw/Repository/covid-cai/dingdong-helper-node/scripts/checkout_cart.js:162:11

Node.js v17.9.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

查看charles session，抓的包头里面并没有ddmc-device-token

**Comment by waynez** [comment]
尝试删除此字段，ios api可以正常调用

```
✗ yarn checkout:normal
yarn run v1.22.18
$ node scripts/checkout_cart
[2022-05-01 10:58:34] [DEBUG] 尝试获取不存在的 Param: device_token
[2022-05-01 10:58:34] [INFO] [] 当前默认地址 : 宝山区宝山镇永乐路422号
[2022-05-01 10:58:34] [DEBUG] 尝试获取不存在的 Param: device_token
[2022-05-01 10:58:35] [DEBUG] 尝试获取不存在的 Param: device_token
[2022-05-01 10:58:35] [INFO] 购物车商品更新: 共 2 件
[2022-05-01 10:58:35] [DEBUG] 尝试获取不存在的 Param: device_token
[2022-05-01 10:58:35] [ERROR] 获取预约时间失败: Error: 没有可预约的时间
[2022-05-01 10:58:35] [DEBUG] Error: 没有可预约的时间
```

本地抓不到应该是由于app版本不同，如果非必需字段的话可以删除，或者README说明一下APP版本。

```
.//service/dingdong/api/applet/get_cart.js:47:            "ddmc-device-token": session.headers["ddmc-device-token"],
.//service/dingdong/api/ios-native/cart_check_all.js:48:            "ddmc-device-token": session.headers["ddmc-device-token"],
.//service/dingdong/api/ios-native/check_order.js:86:            "ddmc-device-token": session.headers["ddmc-device-token"],
.//service/dingdong/api/ios-native/get_multi_reserve_time.js:70:            "ddmc-device-token": session.headers["ddmc-device-token"],
.//service/dingdong/api/ios-native/add_new_order.js:84:            "ddmc-device-token": session.headers["ddmc-device-token"],
.//service/dingdong/api/ios-native/get_address.js:25:            "ddmc-device-token": session.headers["ddmc-device-token"],
```

**Comment by Runc2333** [comment]
只要能获取收货时间就可以正常运行，这个问题我之后修复一下。

**Comment by csrxff** [comment]
刚才又抓了一次包，这次又有ddmc-device-token这个值，不知道这个值是什么情况下会出现或者不出现

**Comment by Runc2333** [comment]
> 刚才又抓了一次包，这次又有ddmc-device-token这个值，不知道这个值是什么情况下会出现或者不出现

对，会增加fallback

**Comment by waynez** [comment]
会不会跟app版本有关系？
