### ISSUE TITLE
需要详细使用步骤教程

### ISSUE THREAD

**Issue by 582635133** [Runc2333/dingdong-helper-node#21]
能提供详细的使用步骤吗，包括抓包

**Comment by Runc2333** [comment]
暂时没有计划撰写详细教程，欢迎其他朋友提pr

**Comment by EsonZhang** [comment]
> 暂时没有计划撰写详细教程，欢迎其他朋友提pr

![e46df1e5c5d5d663a17acd05815c337](https://user-images.githubusercontent.com/48110623/166133269-1f777a63-559b-42b5-82e3-2b04b11a9d66.png)
大佬能帮忙看下这个报错是啥原因吗？

**Comment by Runc2333** [comment]
> > 暂时没有计划撰写详细教程，欢迎其他朋友提pr
> 
> ![e46df1e5c5d5d663a17acd05815c337](https://user-images.githubusercontent.com/48110623/166133269-1f777a63-559b-42b5-82e3-2b04b11a9d66.png) 大佬能帮忙看下这个报错是啥原因吗？

请严格按照readme中的步骤操作，尤其是检查session获取部分
