### ISSUE TITLE
建行叮咚登陆失败，显示请返回建行APP进行登录

### ISSUE THREAD

**Issue by MisakaMikoto86** [Runc2333/dingdong-helper-node#3]

**Comment by Runc2333** [comment]
要登陆建行账号才行。

**Comment by MisakaMikoto86** [comment]
> 



> 要登陆建行账号才行。

是登陆的情况下提示的这个

**Comment by MisakaMikoto86** [comment]
> 你是新下载的建行app吗？

是的，打开其他建行APP里的小程序都行，就这个打不开提示请返回建行App进行登录

**Comment by Runc2333** [comment]
我用新设备下载一个试一下

**Comment by Runc2333** [comment]
新设备首次打开未登录时成功复现，关闭app并登录后成功打开小程序。
请关闭app后重新登陆尝试一次

**Comment by MisakaMikoto86** [comment]
我测试下来交行的买单吧的API也可以正常使用，如果可以的话能把程序更新为读取买单吧API数据嘛

> @MisakaMikoto86 更换新注册账号后，重新登陆也提示`请返回建行APP进行登录`，猜测是必须绑定银行卡才可以。

好的谢谢~

**Comment by Runc2333** [comment]
可以尝试抓取买单吧的`/cart/index`的session并保存到`charles_sessions`目录下，有可能可以直接使用。
成功的话可以告知我一下，我写进readme里。

**Comment by Runc2333** [comment]
已测试可直接使用买单吧Session
