### ISSUE TITLE
捡漏模式订单更新成功，但是提交订单商品总价错误

### ISSUE THREAD

**Issue by KirbyInGitHub** [Runc2333/dingdong-helper-node#35]
<img width="746" alt="image" src="https://user-images.githubusercontent.com/11568406/166170011-338275cd-676a-4dcf-9cbd-498483e0cbb2.png">

开的2线程，100ms

号已黑，获取运力显示拥挤😇

**Comment by shuangmei** [comment]
我是高峰期下单的，也是提示下单失败：商品总价错误
