### ISSUE TITLE
你好，抓包只能找到 https://maicai-apm.ddxq.mobi，找不到readme里的maicai那个地址了

### ISSUE THREAD

**Issue by aaronyao88** [Runc2333/dingdong-helper-node#37]
你好，抓包只能找到 https://maicai-apm.ddxq.mobi，找不到readme里的[maicai](https://maicai.api.ddxq.mobi/cart/index)那个地址了

**Comment by Runc2333** [comment]
请仔细阅读 readme, 若确有困难，可加入 telegram 交流群寻求帮助。

**Comment by iiwen** [comment]
你看我的教程啊，问问题请描述清楚，必要时带上截图https://www.jianshu.com/p/0191790ba30e

**Comment by aaronyao88** [comment]
按照你的简书的教程设置的，唯一不同的用的是superwingy vpn软件
![image](https://user-images.githubusercontent.com/22428246/166190989-deba8392-8573-4d72-b9de-9eb97c556556.png)
![image](https://user-images.githubusercontent.com/22428246/166191007-9cbff018-f0bd-40dc-a4a3-ce157cd6835e.png)

**Comment by Runc2333** [comment]
@aaronyao88 Telegram @weneedfood
