### ISSUE TITLE
im_secret 获取异常

### ISSUE THREAD

**Issue by deluser8** [Runc2333/dingdong-helper-node#39]
在获取im_secret的过程中，发现sunquan相关的api请求只有 /api/v2/user/location/refresh/ 

readme 中第5步的 https://sunquan.api.ddxq.mobi/api/v1/user/detail 找不到了

请问是叮咚换了API嘛？

**Comment by huangchexin** [comment]
我试了还能获取到呀

**Comment by deluser8** [comment]
我的叮咚买菜是v9.49.2这个有影响吗？

以及，我确实能抓到其他的包，比如购物车、会员啥的，并且能看到包的内容（应该不是https的问题）

**Comment by IMLR** [comment]
尝试重新登录APP抓包？
版本无影响，本版算法也是逆向自9.49.2版本，大部分人也是由此版本抓包获取到im_secret

**Comment by deluser8** [comment]
我刚刚升级到最新的 v9.51.0，似乎表现更为奇怪，Charles只能抓到一些无关紧要（图片、apm service）相关的包。API的包都不见了。是因为我ssl设置的原因嘛

**Comment by deluser8** [comment]
但是我京东APP里面想抓的包都能看到倒是

**Comment by IMLR** [comment]
> 我刚刚升级到最新的 v9.51.0，似乎表现更为奇怪，Charles只能抓到一些无关紧要（图片、apm service）相关的包。API的包都不见了。是因为我ssl设置的原因嘛

这个是跳过代理了，你是用shadowrocket抓的吗

**Comment by deluser8** [comment]
没，我直接配置WiFi里面的“代理”

**Comment by huangchexin** [comment]
> 我刚刚升级到最新的 v9.51.0，似乎表现更为奇怪，Charles只能抓到一些无关紧要（图片、apm service）相关的包。API的包都不见了。是因为我ssl设置的原因嘛

用梯子了吗， 之前我也抓不到，看教程倒腾了好久把梯子装好就可以了

**Comment by IMLR** [comment]
> 没，我直接配置WiFi里面的“代理”

请参考文档配置shadowrocket抓包

**Comment by deluser8** [comment]
我先试一下shadowrocket吧，可能是叮咚的关键API不认http proxy。shadowrocket走VPN的接口，应该能覆盖更全
