### ISSUE TITLE
捡漏模式下单失败: 抱歉，同一时间下单人数过多，建议您稍后再试。随后立即被登出

### ISSUE THREAD

**Issue by huangchexin** [Runc2333/dingdong-helper-node#40]
选了个空闲的城市和商品，启动捡漏模式后获取购物车成功，但下单失败，随后显示访问过期，需要重新登录，重复试了几次都是如此：
<img width="570" alt="image" src="https://user-images.githubusercontent.com/18361960/166237395-0d410201-f6f3-4ca7-8e1b-64960f9e7fc3.png">

手动下单能成功。

**Comment by Runc2333** [comment]
@huangchexin 有人能进一步测试一下这个吗

**Comment by huangchexin** [comment]
我测试了两种模式，都是强制退出，APP上面也确实被登出了。
我用昨晚的老版本重新测试了没问题，对比合入了今天修改购物车缓存bug之后就会出现这个问题。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Runc2333/dingdong-helper-node"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月2日(星期一) 晚上10:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Runc2333/dingdong-helper-node] 捡漏模式下单失败: 抱歉，同一时间下单人数过多，建议您稍后再试。随后立即被登出 (Issue #40)





 
你看一下手机上APP是否被强制退出了？
 如果不是试试重新抓包看看？

**Comment by Runc2333** [comment]
最新版100%复现吗？

**Comment by huangchexin** [comment]
> 最新版100%复现吗？

捡漏模式100%复现，高速模式只试了一次，如图：
<img width="687" alt="image" src="https://user-images.githubusercontent.com/18361960/166251353-48349e2a-91df-485c-84c7-7bd18794be42.png">
前提都是可购商品+可下单时间

**Comment by Runc2333** [comment]
稍等，这边尝试复现

**Comment by Runc2333** [comment]
已复现问题，正在排查。
@huangchexin 能说一下是哪个老版本测出来没问题吗？

**Comment by huangchexin** [comment]
> 已复现问题，正在排查。
> @huangchexin 能说一下是哪个老版本测出来没问题吗？

https://github.com/Runc2333/dingdong-helper-node/commit/7df180e7149a1f097db19310fdd2ade4762ad61a   这个修改前应该是没问题的。我拿的是昨晚的版本，没用git拉，好像看不出版本号

**Comment by Runc2333** [comment]
@huangchexin 测试回退这个修改没有解决问题，且在这个修改后我也进行过下单测试成功后才push的。
原因应该是叮咚服务器识别到了部分特征。

**Comment by huangchexin** [comment]
> @huangchexin 测试回退这个修改没有解决问题，且在这个修改后我也进行过下单测试成功后才push的。
> 原因应该是叮咚服务器识别到了部分特征。

给你邮箱私发了昨晚下载的仍可下单的版本，麻烦看看哦

**Comment by Runc2333** [comment]
已提供临时修复方案。
