### ISSUE TITLE
安装ipa提示安装包不完整，请问如何解决？

### ISSUE THREAD

**Issue by HailiangQin** [Runc2333/dingdong-helper-node#44]
@iiwen
我从你提供的链接中尝试安装ipa时，提示说安装包不完整，请问如何解决？

https://www.jianshu.com/p/0191790ba30
![截屏2022-05-03 上午5 16 42](https://user-images.githubusercontent.com/75285547/166329576-68f78f13-d4dd-43a4-a8fc-29d41a09a717.png)
e

**Comment by yechixia0625** [comment]
还是买个号吧 还方便 就两三块钱

**Comment by HailiangQin** [comment]
> 还是买个号吧 还方便 就两三块钱

请问哪里有卖，方便发个链接吗？
