### ISSUE TITLE
is this about the people in guang dong? or dong doing dings? i not know character language.

### ISSUE THREAD

**Issue by lootnath** [Runc2333/dingdong-helper-node#48]
is this about the people in guang dong? or dong doing dings? i not know character language.

**Comment by Runc2333** [comment]
this is a program for people who being lockdown in shanghai, they have to snap up foods in order to fill their stomachs.

**Comment by wwnnrr** [comment]
> this is a program for people who being lockdown in shanghai, they have to snap up foods in order to fill their stomachs.
they have to snap up foods in order to fill their stomachs.
haha haha haha....  hi Guy, you're so humorous， a little serious， but the logic is correct.

**Comment by iiwen** [comment]
@wwnnrr 外国友人来了吗
