### ISSUE TITLE
共享运力计划

### ISSUE THREAD

**Issue by zyw516** [Runc2333/dingdong-helper-node#49]
现在运力接口风控厉害 
有没有一起弄一弄 运力共享的

**Comment by Runc2333** [comment]
@zyw516 可以详细解释一下这么做的意义吗

**Comment by wwnnrr** [comment]
他的意思不会是，一次下一个大的，然后再用跑腿去分吧，不太现实啊。还是说一个人帮其他人一起下单，好像也难啊。

**Comment by zyw516** [comment]
> @zyw516可以详细解释一下这个的意义吗
最近账号开启捡漏模式 每次3s 左右请求一次  大概1-2小时账号就会被黑

当前初步的想法是 我开发一个后台API  支持上报 获取 运力等信息
大家开启捡漏模式 可以把把结果上传  
这样代码中请求官方接口的频率就可以大大降低

如果有多余的小号 我这边也可以写写爬虫  后台更新运力

**Comment by IMLR** [comment]
> > @zyw516可以详细解释一下这个的意义吗
> 
> 最近账号开启捡漏模式 每次3s 左右请求一次 大概1-2小时账号就会被黑
> 
> 当前初步的想法是 我开发一个后台API 支持上报 获取 运力等信息 大家开启捡漏模式 可以把结果上传 这样代码中请求官方接口的频率就可以大大降低
> 
> 如果有多余的小号 我这边也可以写写爬虫 后台更新运力

开始和叮咚比堆账号了是吧🌚

**Comment by wwnnrr** [comment]
> > @zyw516可以详细解释一下这个的意义吗
> 
> 最近账号开启捡漏模式 每次3s 左右请求一次 大概1-2小时账号就会被黑
> 
> 当前初步的想法是 我开发一个后台API 支持上报 获取 运力等信息 大家开启捡漏模式 可以把结果上传 这样代码中请求官方接口的频率就可以大大降低
> 
> 如果有多余的小号 我这边也可以写写爬虫 后台更新运力

那就是说，所有子爬虫，不在对服务器进行访问，而改成对你的服务器进行访问。这样减少发包频率。你这是团伙“作战”啊。

**Comment by zyw516** [comment]
> > > @zyw516可以详细解释一下这个的意义吗
> > 
> > 
> > 最近账号开启捡漏模式 每次3s 左右请求一次 大概1-2小时账号就会被黑
> > 当前初步的想法是 我开发一个后台API 支持上报 获取 运力等信息 大家开启捡漏模式 可以把结果上传 这样代码中请求官方接口的频率就可以大大降低
> > 如果有多余的小号 我这边也可以写写爬虫 后台更新运力
> 
> 开始和叮咚比堆账号了是吧🌚

大家都是被逼的

**Comment by iiwen** [comment]
@wwnnrr 这实现估计很烦，要写后端许多代码和前端代码，感觉没什么价值

**Comment by wwnnrr** [comment]
实际上捡漏，真的效率不高，主要还是6点那一波，我这里目前是30秒就没有东西了。也不知道有多少人在用程序抢的。

**Comment by zyw516** [comment]
> @wwnnrr 这实现估计很烦，要写后端许多代码和前端代码，感觉没什么价值

主要是后端两个接口开发设计  要保证高并发  
如果风控越来越严格  这双是下下策吧

**Comment by iiwen** [comment]
@zyw516 没有实现的价值……这个算了吧

**Comment by Runc2333** [comment]
@zyw516 按照一个账号2小时计算，一天一个站点需要消耗12个账号，上海有多少个站点暂且不表，你觉得有这么多人愿意牺牲账号参与这个运力共享项目吗？
