### ISSUE TITLE
脱壳

### ISSUE THREAD

**Issue by MisakaMikoto86** [Runc2333/dingdong-helper-node#6]

**Comment by iiwen** [comment]
> https://ws28.cn/f/86y2h8hncuv 复制链接到浏览器打开

这是什么请问

**Comment by iiwen** [comment]
> https://ws28.cn/f/86y2h8hncuv 复制链接到浏览器打开

安装不了好像

**Comment by iiwen** [comment]
> https://ws28.cn/f/86y2h8hncuv 复制链接到浏览器打开

@MisakaMikoto86 貌似手机打不开，是叮咚APP吗

**Comment by brightyf88** [comment]
手机不能安装呀？

**Comment by MisakaMikoto86** [comment]
.

**Comment by Runc2333** [comment]
@MisakaMikoto86 已收到，尽快分析。

**Comment by yuejiang** [comment]
> @MisakaMikoto86 已收到，尽快分析。

是逆向so包吗？
