### ISSUE TITLE
 各位，低调一点使用吧 

### ISSUE THREAD

**Issue by czqcs** [Runc2333/dingdong-helper-node#7]
这东西一开源，第二天就能给你封了

**Comment by yuejiang** [comment]
> 希望当您有能力时，可以更多的帮助身边的人。 这即是本项目存在的意义。

282505764，我配置好了，想知道提示没有可用时间是不是就是成功了

**Comment by Runc2333** [comment]
> > 希望当您有能力时，可以更多的帮助身边的人。 这即是本项目存在的意义。
> 
> 282505764，我配置好了，想知道提示没有可用时间是不是就是成功了

已经回复过您了。

**Comment by czqcs** [comment]
那个啥内容已过期，其实叮咚程序员也会用GitHub的，会用都知道怎么看

**Comment by iiwen** [comment]
> 那个啥内容已过期，其实叮咚程序员也会用GitHub的，会用都知道怎么看

……人家也要5·1，况且APP逆向成功了他们也很难搞

**Comment by Runc2333** [comment]
Closed due to update.
