### ISSUE TITLE
高峰有效方案

### ISSUE THREAD

**Issue by iiwen** [Runc2333/dingdong-helper-node#8]
微信抓不到包了，今天早上8：30微信手动点，点进去了，耗时二十几秒，说明微信还有戏，就是抓不到包了不知道有没有大佬能解决
根本的解决就是逆向APP，不知道大佬们进展怎么样
405在大家讨论后彻底解决了，再也没报过
![图片](https://user-images.githubusercontent.com/104404148/165939822-c18c114a-d393-453b-a0a6-99c2be8c75f0.png)
👆这是Java版的，node版也没问题
然后渠道也是有效的，我今天6点程序耗时十几秒抢到了，要改参数，不建议用非常冷门的渠道

**Comment by Runc2333** [comment]
本项目将会适配支付宝渠道，微信渠道因为私有协议抓包困难的问题只能先暂时放弃了。

**Comment by iiwen** [comment]
> 本项目将会适配***渠道，微信渠道因为私有协议抓包困难的问题只能先暂时放弃了。

好叭，我这边就在搞那个渠道，referer、alipayminimark服务器好像没有特别校验，我就跟着Java版稍微改了改就能用了，今天成功了，明天再试一试，建议先不要发渠道名字，官方好像都在盯着，成功了再说吧，否则人家提前加校验了。

**Comment by yuejiang** [comment]
> node版也没问题

282505764，能不能交流一下

**Comment by jzhone** [comment]
今早一直显示前方拥挤请稍后再试，用了3字接口

**Comment by czqcs** [comment]
> > > 微信渠道因为私有协议抓包困难的问题只能先暂时放弃了。
> > 
> > 
> > 我就跟着Java版稍微改了改就能用了
> 
> 请问大佬是如何修改的呢?

无效了。劝你还是死了这条心吧

**Comment by iiwen** [comment]
> 无效了。劝你还是死了这条心吧

死心？逆向进展这么快，为啥死心……

**Comment by yuejiang** [comment]
> > 无效了。劝你还是死了这条心吧
> 
> 死心？逆向进展这么快，为啥死心……

有群吗？可以沟通一下，k8163803

**Comment by Runc2333** [comment]
Closed due to update.
